#!/bin/sh
# This script will create a C file with the epitech Header
# Usage: ./touch_h [file_name]

source ./func

call_script_manager=true
filename=""
headerfiles=()
selected_headerfiles=()

if (( $# < 1 )) || (( $# > 4 )) || (( $# == 3)); then
    echo "Usage: ./addc [-d] [file_name]"
    exit 84
fi
while getopts ":dlfi:" opt; do
    case $opt in
        d)
            call_script_manager=false
            ;;
        \?)
            echo "Invalid option: -$OPTARG"
    esac
done
if $call_script_manager; then
    script-manager
fi

for arg in "$@"; do
    if [[ $arg != -* ]]; then
        filename=$arg
        break
    fi
done
if [ -f "$filename.c" ]; then
    echo "Error: File $filename.c already exists"
    exit 84
fi

touch "$filename.c"
if (( $? != 0 )); then
    echo "Error: Can't create file $filename.c"
    exit 84
fi

add_header $filename "c"
include="include/my.h"
if [ -n "$depth" ]; then
    include="${depth}${include}"
fi
if [ "$3" == "-i" ]; then
    include=$4
fi
for header in $(find . -type f -name "*.h"); do
    headerfiles+=" $header"
done
headerfiles=("" ${headerfiles[@]})
if [ "${#headerfiles[@]}" -gt 1 ]; then
    for index in "${!headerfiles[@]}"; do
        echo "$index: ${headerfiles[$index]}"
    done
    echo "Entrez les numéros des makefiles que vous souhaitez utiliser, séparés par des espaces:"
    read -a selected_indices
    for index in "${selected_indices[@]}"; do
        echo -e "#include \"${headerfiles[$index]}\"" >> $basepwd/"$filename.c"
    done
fi
echo -e "\nint $filename(void)\n{\n    return 0;\n}\n\nint main(void)\n{\n    $filename();\n    return (0);\n}" >> $basepwd/"$filename.c"
G='\033[0;32m'
NC='\033[0m'
RED='\e[0;31m'
echo -e "${G}file $filename.c has been created${NC}"
code $filename.c
echo -e "${RED}Loading resources...${NC}"
