#!/bin/bash
# This script will create a C file with the epitech Header
# Usage: ./touch_h [file_name]

filename=""
if [ "$1" != "-d" ]
then
    script-manager
fi
if (( $# < 1 )) || (( $# > 2 )); then
    echo "Usage: ./addh [-d] [file_name]"
    exit 84
fi

for arg in "$@"
do
    if [[ $arg != -* ]]; then
        filename=$arg
        break
    fi
done

if [ -f "$filename.h" ]; then
    echo "Error: File $filename.h already exists"
    exit 84
fi

touch "$filename.h"
if (( $? != 0 )); then
    echo "Error: Can't create file $filename.h"
    exit 84
fi

basepwd=$(pwd)
currentpwd=$(pwd)
dirname="Unknown"

while [ "$currentpwd" != "/" ]; do
    if [ -d "$currentpwd/.git" ]; then
    dirname=$(git config --get remote.origin.url | sed 's/.*\///' | sed 's/\.git//')
    break
    fi
    currentpwd=$(dirname $currentpwd)
done

year=$(date +%Y)
echo "/*
** EPITECH PROJECT, $year
** $dirname
** File description:
** $filename.h
*/" > $basepwd/"$filename.h"

filename_upper=$(echo "$filename" | tr '[:lower:]' '[:upper:]')
echo -e "#ifndef $filename_upper"_H"\n    #define $filename_upper"_H"\n#endif" >> "$basepwd/$filename.h"
G='\033[0;32m'
NC='\033[0m'
RED='\e[0;31m'
echo -e "${G}file $filename.h has been created${NC}"
code $filename.h
echo -e "${RED}Loading resources...${NC}"