#!/bin/bash
filename=""
#Vérifie s'il n'y a pas le -u
if [ "$1" == "-u" ]
then
    script-manager adds
fi
# Vérifie le nombre d'arguments
if (( $# < 1 )) || (( $# > 2 )); then
    echo "Usage: ./adds [-d] [file_name]"
    exit 84
fi

#Parcour les arguments
for arg in "$@"
do
    #Vérifie que l'argument ne commence pas par un -
    if [[ $arg != -* ]]; then
        filename=$arg
        break
    fi
done
#Ajoute le shebang dans le fichier shell
echo "#!/bin/bash" > "$filename"
#Ajoute toute les permissions au fichier
chmod 755 "$filename"