#!/bin/bash
# This script will create a C file with the epitech Header
# Usage: ./touch_h [file_name]

#Rend utilisable les commandes dans func dans se fichier
#Pour l'image c'est le même principe que le include en c

source func

filename=""
#Vérifie s'il n'y a pas le -d
if [ "$1" != "-d" ]
then
    script-manager
fi
# Vérifie le nombre d'arguments
if (( $# < 1 )) || (( $# > 2 )); then
    echo "Usage: ./addt [-d] [file_name]"
    exit 84
fi

#Parcour les arguments
for arg in "$@"
do
    #Vérifie que l'argument ne commence pas par un -
    if [[ $arg != -* ]]; then
        filename=$arg
        break
    fi
done

# Vérifie si le fichier existe déjà donne une erreur si c'est le cas
if [ -f "$filename.c" ]; then
    echo "Error: File $filename.c already exists"
    exit 84
fi

# Crée le fichier avec le nom donné en argument
touch "$filename.c"
if (( $? != 0 )); then
    echo "Error: Can't create file $filename.c"
    exit 84
fi

# Ajoute le Epi header de Epitech
#add_header filename type
add_header $filename "c"

#Ajoute le fichier .h de criterion
echo -e "#include <criterion/criterion.h>\n\nTest ( my_revstr , check_reverse_string )\n{\n    return;\n}\n" >> $basepwd/"$filename.c"
G='\033[0;32m'
NC='\033[0m'
RED='\e[0;31m'
#Indique à l'utilisateur que le fichier a bien été créé
echo -e "${G}file $filename.c has been created${NC}"
#Lance vscode
code $filename.c
#Indique à l'utilisateur que le fichier est entrain d'être charger
echo -e "${RED}Loading resources...${NC}"