#!/bin/bash

LOCAL_FOLDER="/usr/local/bin"
# Nom du fichier de paramètres
SETTINGS_FILE="$LOCAL_FOLDER/config.ptr"

#Vérifie si le fichier n'existe pas
if [ ! -f "$SETTINGS_FILE" ]; then
    echo "Régénération de la config"
    #Crée le fichier de config
    sudo touch $SETTINGS_FILE
    #Rajoute à qui appartient se fichier
    sudo chown $USER "$SETTINGS_FILE"
    #Donne les droit d'éxécution
    sudo chmod +x "$SETTINGS_FILE"
    
    #Vérifie si le fichier getlib existe
    if [ -f "$LOCAL_FOLDER/getlib" ]; then
        sudo echo "LIB=true" >> $SETTINGS_FILE
    else
        sudo echo "LIB=false" >> $SETTINGS_FILE
    fi
    sudo echo "CODING_STYLE=./coding-style-reports.log" >> $SETTINGS_FILE
    # inclusion_s => /*  (en c)
    # inclusion_i => ** (en c)
    # inclusion_e => */ (en c)    sudo echo "LAUNCH=code"
    # year => 2023
    # filename => nom du fichier
    # extension => se qui suit le nom du fichier .c
    # Pour modifier le epi header vous pouvez modifier le fichier de configuration
    # qui se trouve dans le dossier /usr/local/bin/
    sudo echo "EPI_HEADER=\$inclusion_s\n\$inclusion_i EPITECH PROJECT, \$year\n\$inclusion_i \$repo\n\$inclusion_i File description:\n\$inclusion_i \$filename\$extension\n\$inclusion_e" >> $SETTINGS_FILE
    sudo echo "LAUNCH=code" >> $SETTINGS_FILE
fi
# Vérifie si un argument a été fourni
if [ -z "$1" ]; then
    echo "Erreur: Aucune clé spécifiée."
    exit 1
fi

# Recherche la clé dans le fichier de paramètres
LINE=$(grep "^$1=" $SETTINGS_FILE)

# Vérifie si la clé a été trouvée
if [ -z "$LINE" ]; then
    echo "Erreur: Clé non trouvée."
    exit 1
fi

# Récupère la valeur après le signe égal
VALUE=$(echo $LINE | cut -d '=' -f 2-)

# Affiche la valeur
echo $VALUE