#!/bin/bash

# Nom du fichier de paramètres
SETTINGS_FILE="config.ptr"
LOCAL_FOLDER="/usr/local/bin/"
SETTINGS="$LOCAL_FOLDER/config.ptr"

#Vérifie si le fichier n'existe pas
if [ ! -f "$SETTINGS_FILE" ]; then
    #Vérifie si le fichier getlib existe
    if [ -f "$LOCAL_FOLDER/getlib" ]
        echo "LIB=true" >> $SETTINGS
    else
        echo "LIB=false" >> $SETTINGS
    fi
    echo "CODING_STYLE=\"./coding-style-reports.log\""
    echo "COLOR_CODE=\'\o033[38;5;214m\'" >> $SETTINGS
    echo "COLOR_COM_I=\'\e[32m\'" >> $SETTINGS
    echo "COLOR_COM=\'\o033[32m\'" >> $SETTINGS
    echo "EPI_HEADER=\"\$inclusion_s\n\$inclusion_i EPITECH PROJECT, \$year\n\$inclusion_i \$dirname\n\$inclusion_i File description:\n\$inclusion_i \$filename\$extension\n\$inclusion_e\n\"" >> $SETTINGS
fi
# Vérifie si un argument a été fourni
if [ -z "$1" ]; then
    echo "Erreur: Aucune clé spécifiée."
    exit 1
fi

# Recherche la clé dans le fichier de paramètres
LINE=$(grep "^$1=" $SETTINGS_FILE)

# Vérifie si la clé a été trouvée
if [ -z "$LINE" ]; then
    echo "Erreur: Clé non trouvée."
    exit 1
fi

# Récupère la valeur après le signe égal
VALUE=$(echo $LINE | cut -d '=' -f 2-)

# Affiche la valeur
echo $VALUE