#!/bin/sh
commit=""
file_name=""
call_script_manager=true
move_files=false

display_usage() {
    echo "Usage: $0 [-d] [-f file_name] [-move] commit_message"
    exit 84
}

push_elem() {
    local commit="$1"
    if [ -n "$file_name" ]; then
        git add "$file_name"
    else
        git add .
    fi
    if $call_script_manager; then
        script-manager
    fi
    git commit -m "$commit"
    git push origin main
}

while getopts ":df:m" opt; do
    case $opt in
        d)
            call_script_manager=false
            ;;
        f)
            file_name="$OPTARG"
            ;;
        m)
            move_files=true
            ;;
        \?)
            echo "Invalid option: -$OPTARG"
            display_usage
            ;;
    esac
done
shift $((OPTIND-1))

if [ $# -ne 1 ]; then
    display_usage
fi

commit="$1"

if $move_files; then
    for file in $(find . -type f -name '*.c'); do
        push_elem "[AUTO-MOVE]move $file"
    done
else
    push_elem "$commit"
fi
