#!/bin/sh
commit=""
file_name=""
call_script_manager=false
#display_usage &ffiche l'usage de la commande
display_usage() {
    echo "Usage: $0 [-u] [-f file_name] commit_message"
    exit 84
}
#push_elem permet de push sont code sur github
push_elem() {
    local commit="$1"
    #Vérifie que file_name ne soit pas vide
    #-n permets de vérifier si la variable n'est pas vide
    if [ -n "$file_name" ]; then
        git add "$file_name"
    else
        git add .
    fi
    #Vérifie si call_script_manager est vrai
    if $call_script_manager; then
        #Appel la commande pour mettre à jours les commandes
        script-manager
    fi
    git commit -m "$commit"
    git push origin main
}
#Récuperer les options qui sont dans les arguments
while getopts ":uf:" opt; do
    case $opt in
        u)
            call_script_manager=true
            ;;
        f)
            file_name="$OPTARG"
            ;;
        \?)
            echo "Invalid option: -$OPTARG"
            display_usage
            ;;
    esac
done
shift $((OPTIND-1))

# Vérifie le nombre d'arguments
if [ $# -ne 1 ]; then
    display_usage
fi

commit="$1"
push_elem "$commit"
