#!/bin/bash

# Vérifier si le nombre d'arguments est correct
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <fichier_source.c>"
    exit 1
fi

# Nom du fichier source
fichier_source="$1"

# Utilisation de grep pour extraire les lignes de déclaration de fonction
grep -E '^[[:space:]]*[a-zA-Z_][a-zA-Z0-9_[:space:]]*\*[[:space:]]*[a-zA-Z_][a-zA-Z0-9_[:space:]]*\(.*\)[[:space:]]*{' "$fichier_source"
